### ISSUE TITLE
rename "ch[\d].md" files to "README.md"

### ISSUE THREAD

**Issue by pete911** [jonatasbaldin/grokking-algorithms-golang#2]
Hi, if you renamed `ch[\d].md` files inside subdirectories to `README.md` they would be displayed by default when inside directory by github. This would make it easier to navigate through this project.

**Comment by jonatasbaldin** [comment]
Yeah, you are right! Would u mind sending a PR for that? Having a bit of trouble with time lately heh

**Comment by pete911** [comment]
done
